# MyBB Forge Configuration
# Developer: Austin @ CortaLabs

# Developer information - auto-fills plugin metadata
developer:
  name: "Austin"
  website: "https://cortalabs.com"
  email: "austin@cortalabs.com"

# Default values for new plugins
defaults:
  compatibility: "18*"        # MyBB version compatibility (18* = 1.8.x)
  license: "MIT"              # Default license for new plugins
  visibility: "public"        # Default visibility (public or private)

# Git subtree mappings for plugin/theme repositories
subtrees:
  # MyBB MCP server (this project's subtree)
  mybb_mcp:
    remote: "https://github.com/CortaLabs/mybb_mcp.git"
    branch: main
    squash: true

  # Private plugins (uses env var for remote URL)
  # plugin_manager/plugins/private:
  #   remote_env: PRIVATE_PLUGINS_REMOTE
  #   branch: main
  #   squash: true

# Default plugins to install with fresh MyBB setup
# These are deployed from plugin_manager/plugins/public/
default_plugins:
  - cortex          # Secure template conditionals
  - dice_roller     # BBCode dice rolling for RPG forums

# Disk sync optimization settings
sync:
  debounce_ms: 100              # Milliseconds to wait before syncing changes
  batch_window_ms: 100          # Milliseconds to batch multiple changes together
  enable_cache_refresh: true    # Automatically refresh MyBB cache after sync
