#!/bin/bash
# ============================================
# MyBB Development Environment Setup
# For Ubuntu/Debian on WSL
# ============================================

set -e

echo "=========================================="
echo "MyBB Development Environment Setup"
echo "=========================================="

# Update package list
echo "[1/4] Updating package list..."
sudo apt update

# Install PHP and required extensions
echo "[2/4] Installing PHP 8.3 and extensions..."
sudo apt install -y \
    php8.3 \
    php8.3-cli \
    php8.3-mysql \
    php8.3-gd \
    php8.3-mbstring \
    php8.3-xml \
    php8.3-curl \
    php8.3-zip

# Install MariaDB
echo "[3/4] Installing MariaDB..."
sudo apt install -y mariadb-server mariadb-client

# Start MariaDB service
echo "[4/4] Starting MariaDB service..."
sudo service mariadb start

# Create MyBB database and user
echo ""
echo "=========================================="
echo "Setting up MyBB database..."
echo "=========================================="

# Generate a random password for dev (you can change this)
MYBB_DB_PASS="mybb_dev_$(openssl rand -hex 4)"

sudo mariadb -e "CREATE DATABASE IF NOT EXISTS mybb_dev CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
sudo mariadb -e "CREATE USER IF NOT EXISTS 'mybb_user'@'localhost' IDENTIFIED BY '${MYBB_DB_PASS}';"
sudo mariadb -e "GRANT ALL PRIVILEGES ON mybb_dev.* TO 'mybb_user'@'localhost';"
sudo mariadb -e "FLUSH PRIVILEGES;"

echo ""
echo "=========================================="
echo "Setup Complete!"
echo "=========================================="
echo ""
echo "Database credentials (save these!):"
echo "  Host:     localhost"
echo "  Database: mybb_dev"
echo "  User:     mybb_user"
echo "  Password: ${MYBB_DB_PASS}"
echo ""
echo "Next steps:"
echo "  1. Run: ./start_mybb.sh"
echo "  2. Open: http://localhost:8022/install/"
echo "  3. Use the database credentials above during install"
echo ""
echo "Tip: Save the password to a .env file (already gitignored)"
echo ""

# Save credentials to .env file
cat > .env << EOF
# MyBB Development Database Credentials
# Generated by setup_dev_env.sh
MYBB_DB_HOST=localhost
MYBB_DB_NAME=mybb_dev
MYBB_DB_USER=mybb_user
MYBB_DB_PASS=${MYBB_DB_PASS}
MYBB_DB_PREFIX=mybb_
MYBB_PORT=8022
EOF

echo "Credentials saved to .env file"
